version: '3'
services:
  bot-status:
    container_name: bot-status
    image: python:3.5
    # ports:
    #   - "3100:3100"
    volumes:
      - ./:/bot/
    command: sh -c "cd /bot && pip install -r requirements.txt && python bot.py"
    restart: always
  # mongoWeb:
  #   container_name: mongoWeb
  #   image: mongo
  #   command: sh -c "mongo test-web-sirius --eval \"db.dropDatabase()\""
  #   restart: always
